services:
  - type: web
    name: carrier-campaign-dashboard
    env: python
    region: california
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    healthCheckPath: /_stcore/health
    autoDeploy: true